version: '3.8'

services:

  api:
    image: 'spring-api:latest'
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-server:5432/db-full-secure
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
