version:  '3.8'

services:

  db-server:
    image: postgres:14.3
    container_name: db-server
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=db-full-secure
    ports:
      - "5432:5432"
    volumes:
      - ../db-dumps/light_dump_of_08_03_2024.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - app-network

  db-client:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "5050:80"
    depends_on:
      - db-server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
