server:
  port: 9090
  address: 0.0.0.0

spring:

  datasource:
    username: postgres
    password: 123456
    # URL localhost | postgres
    url: jdbc:postgresql://localhost:5432/db-pix-pass
    driver-class-name: org.postgresql.Driver

  # flyway:
  #   enabled: true
  #   locations: classpath:db/migration
  #   baselineOnMigrate: true
  #   validateOnMigrate: false
  #   schemas: public
  #   table: flyway_schema_history

  jpa:
    hibernate:
      ddl-auto: create-drop # update # create-drop 
    # show-sql: true
    properties:
      hibernate:
        "[format_sql]": true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

api:
  path: ../pix-pass-server
